version: '3'

services:

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    ports:
      - 3000:3000
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  pg_data:
